//! [junction-endpoint] EXPERIMENTAL, opt-in, and self-contained.
//!
//! Down-weights alignments whose transcript-coordinate boundary coincides with
//! an *internal* splice junction of the transcript they are aligned to.
//!
//! Rationale: a molecule generated by transcript `t` has no reason to stop at an
//! interior exon boundary of `t`. When an alignment does end there, the endpoint
//! is usually better explained by a sibling isoform that *terminates* at that
//! position. On NanoSim simulations with read-level truth, an alignment boundary
//! landing exactly on an internal junction is ~9.9x more likely to belong to a
//! decoy transcript than to the true source (3' end; 7.1x at the 5' end).
//!
//! To remove this feature entirely, delete this file and the four blocks tagged
//! `[junction-endpoint]` (grep for the tag): the `pub mod` line in `src/util.rs`,
//! the CLI arguments in `src/prog_opts.rs`, and the application block in
//! `src/bulk.rs`.

use std::collections::HashMap;
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

use crate::util::oarfish_types::InMemoryAlignmentStore;

/// Internal splice-junction offsets, in transcript coordinates, per transcript.
pub struct JunctionIndex {
    /// indexed by oarfish transcript id; empty when unknown or single-exon
    per_txp: Vec<Vec<u32>>,
    pub n_with_junctions: usize,
    pub n_unmatched: usize,
    pub n_length_mismatch: usize,
}

/// Normalise a transcript identifier: take the field before `|`, then drop a
/// trailing `.<digits>` accession version.
fn norm(name: &str) -> &str {
    let base = name.split('|').next().unwrap_or(name);
    match base.rfind('.') {
        Some(i) if i + 1 < base.len() && base[i + 1..].bytes().all(|b| b.is_ascii_digit()) => {
            &base[..i]
        }
        _ => base,
    }
}

fn attr<'a>(attrs: &'a str, key: &str) -> Option<&'a str> {
    let pat = format!("{key} \"");
    let i = attrs.find(&pat)? + pat.len();
    let rest = &attrs[i..];
    let j = rest.find('"')?;
    Some(&rest[..j])
}

impl JunctionIndex {
    /// Build from a GTF. `txps_name` is oarfish's transcript order; `txp_len`
    /// their lengths, used to reject transcripts whose annotated exonic length
    /// disagrees with the reference sequence (RefSeq has ~2.8% such cases, where
    /// transcript-coordinate offsets would be mis-registered).
    pub fn from_gtf(
        gtf: &Path,
        txps_name: &[String],
        txp_len: &[usize],
    ) -> anyhow::Result<Self> {
        let mut want: HashMap<&str, usize> = HashMap::with_capacity(txps_name.len());
        for (i, n) in txps_name.iter().enumerate() {
            want.insert(norm(n), i);
        }

        // exon intervals per wanted transcript
        let mut exons: HashMap<usize, Vec<(u64, u64)>> = HashMap::new();
        let mut minus: HashMap<usize, bool> = HashMap::new();
        let f = File::open(gtf)?;
        for line in BufReader::new(f).lines() {
            let line = line?;
            if line.starts_with('#') {
                continue;
            }
            let mut it = line.split('\t');
            let (_seq, _src, feat, start, end, _score, strand, _frame, attrs) = (
                it.next(),
                it.next(),
                it.next(),
                it.next(),
                it.next(),
                it.next(),
                it.next(),
                it.next(),
                it.next(),
            );
            if feat != Some("exon") {
                continue;
            }
            let (Some(start), Some(end), Some(attrs)) = (start, end, attrs) else {
                continue;
            };
            let Some(tid) = attr(attrs, "transcript_id") else {
                continue;
            };
            let Some(&idx) = want.get(norm(tid)) else {
                continue;
            };
            let (Ok(s), Ok(e)) = (start.parse::<u64>(), end.parse::<u64>()) else {
                continue;
            };
            exons.entry(idx).or_default().push((s, e));
            if strand == Some("-") {
                minus.insert(idx, true);
            }
        }

        let mut per_txp = vec![Vec::new(); txps_name.len()];
        let mut n_with = 0usize;
        let mut n_mismatch = 0usize;
        for (idx, mut es) in exons {
            es.sort_unstable();
            if *minus.get(&idx).unwrap_or(&false) {
                es.reverse();
            }
            let total: u64 = es.iter().map(|(s, e)| e - s + 1).sum();
            if total as usize != txp_len[idx] {
                n_mismatch += 1;
                continue;
            }
            if es.len() < 2 {
                continue;
            }
            let mut acc = 0u64;
            let mut js = Vec::with_capacity(es.len() - 1);
            for (s, e) in es.iter().take(es.len() - 1) {
                acc += e - s + 1;
                js.push(acc as u32);
            }
            per_txp[idx] = js;
            n_with += 1;
        }
        let n_unmatched = txps_name.len() - n_with - n_mismatch;
        Ok(Self {
            per_txp,
            n_with_junctions: n_with,
            n_unmatched,
            n_length_mismatch: n_mismatch,
        })
    }

    #[inline]
    fn near(&self, txp: usize, x: u32, window: u32) -> bool {
        let js = &self.per_txp[txp];
        if js.is_empty() {
            return false;
        }
        let i = js.partition_point(|&j| j < x);
        if i < js.len() && js[i] - x <= window {
            return true;
        }
        if i > 0 && x - js[i - 1] <= window {
            return true;
        }
        false
    }
}

/// Multiply the coverage probability of every junction-terminated alignment by
/// `exp(-lambda)`. Returns (penalised, total) alignment counts.
pub fn apply(
    store: &mut InMemoryAlignmentStore,
    idx: &JunctionIndex,
    window: u32,
    lambda: f64,
) -> (usize, usize) {
    let pen = (-lambda).exp();
    let total = store.alignments.len();
    if store.coverage_probabilities.len() != total {
        // coverage modelling produced no per-alignment vector; nothing to scale
        return (0, total);
    }
    let mut hit = 0usize;
    for (i, aln) in store.alignments.iter().enumerate() {
        let t = aln.ref_id as usize;
        if idx.near(t, aln.start, window) || idx.near(t, aln.end, window) {
            store.coverage_probabilities[i] *= pen;
            hit += 1;
        }
    }
    (hit, total)
}
