//! PacBio-specific physical endpoint observation model.
//!
//! A retained alignment is generated by one of four latent molecule states:
//! intact, 5'-truncated, 3'-truncated, or broken at both ends. Intact endpoints
//! follow nucleotide-scale truncated exponentials; truncated endpoints are
//! deliberately diffuse. Mixture weights and intact tolerances are learned
//! from uniquely assigned reads with informative priors.

use crate::util::endpoint_probability::AdaptiveEndpointProbabilities;
use crate::util::oarfish_types::{AlnInfo, InMemoryAlignmentStore, TranscriptInfo};
use bio_types::strand::Strand;
use serde::Serialize;

const COMPONENTS: usize = 4;
const MIXTURE_PRIOR: [f64; COMPONENTS] = [80.0, 5.0, 5.0, 10.0];
const TAU_PRIOR_MASS: f64 = 100.0;
const TAU_PRIOR: f64 = 25.0;
const MIN_TAU: f64 = 3.0;
const MAX_TAU: f64 = 200.0;
const NESTED_LENGTH_DIFFERENCE_NT: usize = 5_000;

#[derive(Debug, Clone)]
struct PhysicalModel {
    mixture: [f64; COMPONENTS],
    tau5: f64,
    tau3: f64,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct PhysicalEndpointDiagnostics {
    pub training_reads: usize,
    pub intact_fraction: f64,
    pub five_prime_truncated_fraction: f64,
    pub three_prime_truncated_fraction: f64,
    pub broken_fraction: f64,
    pub five_prime_tolerance_nt: f64,
    pub three_prime_tolerance_nt: f64,
    pub endpoint_unidentifiable_reads: usize,
    pub protected_transcripts: usize,
}

fn gaps_nt(aln: &AlnInfo, len: usize) -> (f64, f64) {
    let left = aln.start.saturating_sub(1) as f64;
    let right = len.saturating_sub(aln.end as usize) as f64;
    if aln.strand == Strand::Reverse {
        (right, left)
    } else {
        (left, right)
    }
}

fn intact_density(gap: f64, len: usize, tau: f64) -> f64 {
    let normalizer = tau * (1.0 - (-((len + 1) as f64) / tau).exp());
    (-gap / tau).exp() / normalizer.max(f64::MIN_POSITIVE)
}

fn diffuse_density(len: usize) -> f64 {
    1.0 / (len + 1) as f64
}

fn mark_unidentifiable_short_candidates(
    alignments: &[AlnInfo],
    txps: &[TranscriptInfo],
    protected: &mut [bool],
) -> bool {
    let mut found = false;
    for short in alignments {
        let short_len = txps[short.ref_id as usize].len.get();
        if alignments.iter().any(|long| {
            let long_len = txps[long.ref_id as usize].len.get();
            long_len >= short_len.saturating_add(NESTED_LENGTH_DIFFERENCE_NT)
        }) {
            protected[short.ref_id as usize] = true;
            found = true;
        }
    }
    found
}

impl PhysicalModel {
    fn component_likelihoods(&self, aln: &AlnInfo, len: usize) -> [f64; COMPONENTS] {
        let (g5, g3) = gaps_nt(aln, len);
        let i5 = intact_density(g5, len, self.tau5);
        let i3 = intact_density(g3, len, self.tau3);
        let diffuse = diffuse_density(len);
        [i5 * i3, diffuse * i3, i5 * diffuse, diffuse * diffuse]
    }

    fn likelihood(&self, aln: &AlnInfo, len: usize) -> f64 {
        self.component_likelihoods(aln, len)
            .iter()
            .zip(self.mixture)
            .map(|(likelihood, weight)| likelihood * weight)
            .sum::<f64>()
            .max(f64::MIN_POSITIVE)
    }
}

fn fit(observations: &[(&AlnInfo, usize)]) -> PhysicalModel {
    let mut model = PhysicalModel {
        mixture: [0.8, 0.05, 0.05, 0.1],
        tau5: TAU_PRIOR,
        tau3: TAU_PRIOR,
    };
    for _ in 0..50 {
        let mut component_mass = [0.0; COMPONENTS];
        let mut gap5_mass = 0.0;
        let mut gap3_mass = 0.0;
        let mut intact5_mass = 0.0;
        let mut intact3_mass = 0.0;
        for &(aln, len) in observations {
            let likelihoods = model.component_likelihoods(aln, len);
            let weighted = std::array::from_fn::<_, COMPONENTS, _>(|index| {
                model.mixture[index] * likelihoods[index]
            });
            let total = weighted.iter().sum::<f64>().max(f64::MIN_POSITIVE);
            let responsibility = weighted.map(|value| value / total);
            for index in 0..COMPONENTS {
                component_mass[index] += responsibility[index];
            }
            let (g5, g3) = gaps_nt(aln, len);
            let r5 = responsibility[0] + responsibility[2];
            let r3 = responsibility[0] + responsibility[1];
            gap5_mass += r5 * g5;
            gap3_mass += r3 * g3;
            intact5_mass += r5;
            intact3_mass += r3;
        }
        let total = component_mass
            .iter()
            .zip(MIXTURE_PRIOR)
            .map(|(mass, prior)| mass + prior)
            .sum::<f64>();
        for index in 0..COMPONENTS {
            model.mixture[index] = (component_mass[index] + MIXTURE_PRIOR[index]) / total;
        }
        model.tau5 = ((gap5_mass + TAU_PRIOR_MASS * TAU_PRIOR) / (intact5_mass + TAU_PRIOR_MASS))
            .clamp(MIN_TAU, MAX_TAU);
        model.tau3 = ((gap3_mass + TAU_PRIOR_MASS * TAU_PRIOR) / (intact3_mass + TAU_PRIOR_MASS))
            .clamp(MIN_TAU, MAX_TAU);
    }
    model
}

pub(crate) fn physical_endpoint_probabilities(
    store: &InMemoryAlignmentStore,
    txps: &[TranscriptInfo],
) -> (
    AdaptiveEndpointProbabilities,
    PhysicalEndpointDiagnostics,
    Vec<bool>,
) {
    let observations: Vec<_> = store
        .iter()
        .filter_map(|(alignments, _, _)| match alignments {
            [alignment] => Some((alignment, txps[alignment.ref_id as usize].len.get())),
            _ => None,
        })
        .collect();
    let model = fit(&observations);
    let mut probabilities = Vec::with_capacity(store.total_len());
    let support = observations.len() as f64 / (observations.len() as f64 + 1_000.0);
    let mut support_gates = Vec::with_capacity(store.len());
    let mut protected = vec![false; txps.len()];
    let mut endpoint_unidentifiable_reads = 0;
    for (alignments, _, _) in store.iter() {
        if mark_unidentifiable_short_candidates(alignments, txps, &mut protected) {
            endpoint_unidentifiable_reads += 1;
        }
        let mut local: Vec<_> = alignments
            .iter()
            .map(|alignment| model.likelihood(alignment, txps[alignment.ref_id as usize].len.get()))
            .collect();
        let total = local.iter().sum::<f64>();
        if total > 0.0 && total.is_finite() {
            local.iter_mut().for_each(|value| *value /= total);
        } else if !local.is_empty() {
            let uniform = 1.0 / local.len() as f64;
            local.fill(uniform);
        }
        probabilities.extend(local);
        support_gates.push(support as f32);
    }
    let diagnostics = PhysicalEndpointDiagnostics {
        training_reads: observations.len(),
        intact_fraction: model.mixture[0],
        five_prime_truncated_fraction: model.mixture[1],
        three_prime_truncated_fraction: model.mixture[2],
        broken_fraction: model.mixture[3],
        five_prime_tolerance_nt: model.tau5,
        three_prime_tolerance_nt: model.tau3,
        endpoint_unidentifiable_reads,
        protected_transcripts: protected.iter().filter(|&&value| value).count(),
    };
    (
        AdaptiveEndpointProbabilities {
            probabilities,
            support_gates,
            training_reads: observations.len(),
            selected_prior_mass: MIXTURE_PRIOR.iter().sum(),
            folds: 1,
            uncertainty_gates: Vec::new(),
            ambiguous_training_reads: 0,
        },
        diagnostics,
        protected,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn alignment(start: u32, end: u32) -> AlnInfo {
        AlnInfo {
            ref_id: 0,
            start,
            end,
            prob: 0.0,
            strand: Strand::Forward,
        }
    }

    #[test]
    fn intact_component_prefers_both_expected_ends() {
        let model = PhysicalModel {
            mixture: [1.0, 0.0, 0.0, 0.0],
            tau5: 25.0,
            tau3: 25.0,
        };
        assert!(
            model.likelihood(&alignment(1, 1000), 1000)
                > model.likelihood(&alignment(101, 900), 1000)
        );
    }

    #[test]
    fn strand_aware_gaps_swap_physical_ends() {
        let forward = alignment(11, 1000);
        let mut reverse = forward.clone();
        reverse.strand = Strand::Reverse;
        assert_eq!(gaps_nt(&forward, 1000), (10.0, 0.0));
        assert_eq!(gaps_nt(&reverse, 1000), (0.0, 10.0));
    }

    #[test]
    fn fit_recovers_intact_dominance_from_full_length_reads() {
        let alignments: Vec<_> = (0..200).map(|_| alignment(1, 1000)).collect();
        let observations: Vec<_> = alignments.iter().map(|aln| (aln, 1000)).collect();
        let model = fit(&observations);
        assert!(model.mixture[0] > 0.9);
        assert!(model.tau5 <= TAU_PRIOR && model.tau3 <= TAU_PRIOR);
    }

    #[test]
    fn nested_full_length_candidate_is_marked_for_creation_protection() {
        let short = alignment(1, 1000);
        let mut long = alignment(501, 1500);
        long.ref_id = 1;
        let txps = vec![
            TranscriptInfo::with_len(std::num::NonZeroUsize::new(1000).unwrap()),
            TranscriptInfo::with_len(std::num::NonZeroUsize::new(7000).unwrap()),
        ];
        let mut protected = vec![false; 2];
        assert!(mark_unidentifiable_short_candidates(
            &[short, long],
            &txps,
            &mut protected
        ));
        assert_eq!(protected, vec![true, false]);
    }
}
